"""
TNEENWH — Python client for the WhatsApp HTTP API.

Quick start::

    import tneenwh

    tneenwh.configure(base_url="https://your-host", api_key="...")
    tneenwh.set_session("session-uuid", "channel-secret-hex")
    tneenwh.login(email="you@example.com", password="...")
    tneenwh.send_text("201234567890@c.us", "Hello")

See ``docs/TNEENWH-SDK.md`` in the repo for full documentation.
"""

from .api import (
    admin_sessions,
    admin_users,
    assistant_chat,
    assistant_status,
    channel_secrets,
    create_group,
    docs_routes,
    download_inbound_media,
    generate_otp,
    get_channel_secret,
    group_admins_demote,
    group_admins_promote,
    group_delete_picture,
    group_get,
    group_invite_code,
    group_leave,
    group_membership_approve,
    group_membership_reject,
    group_membership_requests,
    group_participants_add,
    group_participants_remove,
    group_revoke_invite,
    group_set_add_members_admins_only,
    group_set_description,
    group_set_info_admins_only,
    group_set_messages_admins_only,
    group_set_picture,
    group_set_subject,
    health,
    login,
    logout,
    me,
    openapi_spec,
    profile,
    refresh_session_qr,
    request_signup_otp,
    rotate_channel_secret,
    rotate_swagger_portal,
    send_list_message,
    send_media,
    send_message,
    send_text,
    session,
    session_calls,
    session_create,
    session_delete,
    session_details,
    session_disconnect,
    session_events,
    session_incoming,
    session_qr,
    sessions_list,
    session_status,
    session_update,
    set_status,
    set_webhook,
    signup_send_otp,
    signup_verify,
    v1_send_message,
    v1_sessions_list,
    verify_otp,
)
from .otp_template import OtpNotificationParams, format_otp_notification_message
from .channel import Channel
from .config import (
    configure,
    get_config,
    set_api_key,
    set_apikey,
    set_base_url,
    set_bearer_token,
    set_session,
)
from .exceptions import (
    FeatureNotSupportedError,
    TneenwhApiError,
    is_api_error,
    is_feature_not_supported,
)

__version__ = "0.1.1"

__all__ = [
    "Channel",
    "FeatureNotSupportedError",
    "OtpNotificationParams",
    "TneenwhApiError",
    "format_otp_notification_message",
    "is_api_error",
    "is_feature_not_supported",
    "admin_sessions",
    "admin_users",
    "assistant_chat",
    "assistant_status",
    "channel_secrets",
    "configure",
    "create_group",
    "docs_routes",
    "download_inbound_media",
    "generate_otp",
    "get_channel_secret",
    "get_config",
    "group_admins_demote",
    "group_admins_promote",
    "group_delete_picture",
    "group_get",
    "group_invite_code",
    "group_leave",
    "group_membership_approve",
    "group_membership_reject",
    "group_membership_requests",
    "group_participants_add",
    "group_participants_remove",
    "group_revoke_invite",
    "group_set_add_members_admins_only",
    "group_set_description",
    "group_set_info_admins_only",
    "group_set_messages_admins_only",
    "group_set_picture",
    "group_set_subject",
    "health",
    "login",
    "logout",
    "me",
    "openapi_spec",
    "profile",
    "refresh_session_qr",
    "request_signup_otp",
    "rotate_channel_secret",
    "rotate_swagger_portal",
    "send_list_message",
    "send_media",
    "send_message",
    "send_text",
    "session",
    "session_calls",
    "session_create",
    "session_delete",
    "session_details",
    "session_disconnect",
    "session_events",
    "session_incoming",
    "session_qr",
    "sessions_list",
    "session_status",
    "session_update",
    "set_api_key",
    "set_apikey",
    "set_base_url",
    "set_bearer_token",
    "set_session",
    "set_status",
    "set_webhook",
    "signup_send_otp",
    "signup_verify",
    "v1_send_message",
    "v1_sessions_list",
    "verify_otp",
]
